# -*- coding: utf-8 -*-
"""Data_Visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J23f48z294pl2nBpzHz-9zcXQAbXa3zf
"""

import pandas as pd
import matplotlib.pyplot as plt

iris = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

plt.figure(figsize=(8, 8))
iris['species'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, colors=['#ff9999', '#66b3ff', '#99ff99'])
plt.title('Distribution of Iris Species')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris_data = pd.read_csv(iris_url, header=None, names=column_names)

class_means = iris_data.groupby('class').mean()

class_means.plot(kind='bar', figsize=(10, 6), colormap='viridis')
plt.title('Mean Measurements for Each Iris Class')
plt.xlabel('Iris Class')
plt.ylabel('Mean Measurement')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris_data = pd.read_csv(iris_url, header=None, names=column_names)

iris_data.hist(figsize=(12, 8), bins=20, color='skyblue', edgecolor='black', linewidth=1.2)
plt.suptitle('Histograms of Iris Dataset Features', y=1.02, size=16)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris_data = pd.read_csv(iris_url, header=None, names=column_names)

correlation_matrix = iris_data.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=.5)
plt.title('Correlation Heatmap of Iris Dataset Features')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris_data = pd.read_csv(iris_url, header=None, names=column_names)

sns.scatterplot(x='sepal_length', y='sepal_width', hue='class', data=iris_data)
plt.title('Scatter Plot of Sepal Length vs Sepal Width')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris_data = pd.read_csv(iris_url, header=None, names=column_names)

plt.figure(figsize=(10, 6))
sns.boxplot(x='class', y='sepal_length', data=iris_data)
plt.title('Boxplot of Sepal Length by Iris Class')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris_data = pd.read_csv(iris_url, header=None, names=column_names)

plt.figure(figsize=(10, 6))
iris_data.boxplot(column=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], by='class', layout=(2, 2), figsize=(12, 8))
plt.suptitle("Boxplot of Iris Dataset by Class", y=1.02)
plt.show()